#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include <gtest/gtest.h>
#include <wpi/datalog/DataLogReader.hpp>
#include <wpi/framework/RobotBase.hpp>
#include <wpi/nt/NetworkTableInstance.hpp>
#include <wpi/util/MemoryBuffer.hpp>
#include <wpi/util/json.hpp>

#include "akit/log/LogTable.h"
#include "akit/networktables/NT4Publisher.h"
#include "akit/wpilog/WPILOGConstants.h"
#include "akit/wpilog/WPILOGWriter.h"

namespace {

    using akit::LogStorage;
    using akit::LogTable;
    using akit::LogValue;
    using akit::networktables::NT4Publisher;
    using akit::wpilog::WPILOGWriter;

    std::filesystem::path MakeTempDir(const std::string& name) {
        const auto path = std::filesystem::temp_directory_path() / name;
        std::error_code ec;
        std::filesystem::remove_all(path, ec);
        std::filesystem::create_directories(path, ec);
        return path;
    }

    std::string MetadataWithUnit(const std::string& unit) {
        std::string metadata{akit::WPILOGConstants::kEntryMetadataUnits};
        metadata.replace(metadata.find("$UNITSTR"), 8, unit);
        return metadata;
    }

    TEST(WPILOGWriterParityTest, UnitMetadataChangesEmitSetMetadataRecord) {
        const auto dir = MakeTempDir("akit_writer_metadata_test");
        const auto logPath = dir / "metadata.wpilog";

        {
            WPILOGWriter writer(logPath.string(), WPILOGWriter::AdvantageScopeOpenBehavior::kNever);
            writer.Start();

            LogStorage firstStorage;
            LogTable firstTable(firstStorage);
            firstTable.SetTimestamp(100);
            firstTable.Put("Measured", 1.0, "A");
            writer.PutTable(firstTable);

            LogStorage secondStorage;
            LogTable secondTable(secondStorage);
            secondTable.SetTimestamp(200);
            secondTable.Put("Measured", 1.0, "V");
            writer.PutTable(secondTable);

            writer.End();
        }

        auto buffer = wpi::util::MemoryBuffer::GetFile(logPath.string());
        ASSERT_TRUE(buffer.has_value());

        wpi::log::DataLogReader reader(std::move(buffer).value());
        ASSERT_TRUE(reader.IsValid());

        int measuredEntry = -1;
        int metadataUpdates = 0;
        bool sawInitialMetadata = false;
        bool sawUpdatedMetadata = false;

        for (const auto& record : reader) {
            if (record.IsStart()) {
                wpi::log::StartRecordData startData;
                ASSERT_TRUE(record.GetStartData(&startData));
                if (startData.name == "/Measured") {
                    measuredEntry = startData.entry;
                    sawInitialMetadata = std::string(startData.metadata) == MetadataWithUnit("A");
                }
            } else if (record.IsSetMetadata()) {
                wpi::log::MetadataRecordData metadataData;
                ASSERT_TRUE(record.GetSetMetadataData(&metadataData));
                if (metadataData.entry == measuredEntry) {
                    metadataUpdates++;
                    sawUpdatedMetadata = std::string(metadataData.metadata) == MetadataWithUnit("V");
                }
            }
        }

        EXPECT_NE(measuredEntry, -1);
        EXPECT_TRUE(sawInitialMetadata);
        EXPECT_TRUE(sawUpdatedMetadata);
        EXPECT_EQ(metadataUpdates, 1);
    }

    TEST(WPILOGWriterParityTest, AutoGeneratedFilenameAndAdvantageScopePathMatchJavaShape) {
        if (!wpi::RobotBase::IsSimulation()) GTEST_SKIP();

        const auto dir = MakeTempDir("akit_writer_autoname_test") / "nested" / "logs";
        const auto ascopePath = std::filesystem::temp_directory_path() / "ascope-log-path.txt";
        std::error_code ec;
        std::filesystem::remove(ascopePath, ec);

        {
            WPILOGWriter writer(dir.string(), WPILOGWriter::AdvantageScopeOpenBehavior::kAlways);
            writer.Start();
            EXPECT_FALSE(std::filesystem::exists(ascopePath));
            writer.End();
        }

        std::vector<std::filesystem::path> logFiles;
        for (const auto& entry : std::filesystem::directory_iterator(dir)) {
            if (entry.path().extension() == ".wpilog") {
                logFiles.push_back(entry.path());
            }
        }

        ASSERT_EQ(logFiles.size(), 1u);
        EXPECT_EQ(logFiles[0].filename().string().rfind("akit_", 0), 0u);
        EXPECT_EQ(logFiles[0].extension(), ".wpilog");

        ASSERT_TRUE(std::filesystem::exists(ascopePath));
        std::ifstream reader(ascopePath);
        std::string publishedPath;
        std::getline(reader, publishedPath);
        EXPECT_EQ(std::filesystem::path(publishedPath).filename(), logFiles[0].filename());
    }

    TEST(NT4PublisherParityTest, SchemaTopicsPublishUnderNormalizedAdvantageKitKeys) {
        auto inst = wpi::nt::NetworkTableInstance::GetDefault();
        const std::string schemaTopicName = "/AdvantageKit/.schema/test_schema_key";

        NT4Publisher publisher;

        LogStorage storage;
        LogTable table(storage);
        table.SetTimestamp(1);
        storage.values.emplace("/.schema/test_schema_key", LogValue{std::vector<uint8_t>{1, 2, 3}, "structschema"});
        publisher.PutTable(table);

        bool foundSchemaTopic = false;
        for (const auto& topic : inst.GetTopics("/AdvantageKit")) {
            if (topic.GetName() == schemaTopicName) {
                foundSchemaTopic = true;
                EXPECT_EQ(topic.GetTypeString(), "structschema");
            }
        }

        EXPECT_TRUE(foundSchemaTopic);
    }

    TEST(NT4PublisherParityTest, TopicsDeclareImmutabilityAndTimestampUnit) {
        NT4Publisher publisher;

        LogStorage storage;
        LogTable table(storage);
        table.SetTimestamp(1'000'000);
        table.Put("PublishedValue", 3.0);
        publisher.PutTable(table);

        auto instance = wpi::nt::NetworkTableInstance::GetDefault();
        const auto timestampTopic = instance.GetTopic("/AdvantageKit/Timestamp");
        EXPECT_EQ(timestampTopic.GetProperty("unit").get_string(), "nanoseconds");
        EXPECT_EQ(timestampTopic.GetProperty("mutable").get_string(), "false");
        EXPECT_EQ(instance.GetTopic("/AdvantageKit/PublishedValue").GetProperty("mutable").get_string(), "false");
    }
} // namespace
